import { disconnect } from "process";

// import { Background } from './Background';
export const LoaderConfig = {
    // frame : "/src/sprites/SlotMachine_3x5.png",
    Background: "src/sprites/Background.jpg",
    gameBg: "src/sprites/Background.jpg",
    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",
    maxBetBtn :  "/src/sprites/ButtonMaxBet_1.png",
    maxBetBtOnPressed :  "/src/sprites/ButtonMaxBetHover_1.png",
    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed : "/src/sprites/ButtonAutoSpinHover_1.png",
    BetPanel :  "/src/sprites/PanelTotalBet.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    mBtn  :  "/src/sprites/ButtonMinus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    mBtnH  :  "/src/sprites/ButtonMinusHover.png",
    lines :  "/src/sprites/PanelLines.png",
    winPanel :  "/src/sprites/PanelWin.png",
    winPanel1:  "/src/sprites/PanelWin1.png",        
    balancePanel :  "/src/sprites/PanelBalance.png",
    doubleButton: "src/sprites/doubleButton.png",
    doubleButtonPressed : "src/sprites/doubleButtonPressed.png",
    winBg: "src/sprites/winBg.png",
    MenuBtn :  "/src/sprites/ButtonMenu.png",
    MenuBtnH :  "/src/sprites/ButtonMenuHover.png",
    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png",
    linesNumber: "src/sprites/LinesNumber.png",

    inofIcon1: "src/sprites/info1.png",
    inofIcon2: "src/sprites/info2.png",
    inofIcon3: "src/sprites/info3.png",
    inofIcon4: "src/sprites/info4.png",
    inofIcon5: "src/sprites/info5.png",
    inofIcon6: "src/sprites/info6.png",
    inofIcon7: "src/sprites/info7.png",
    inofIcon8: "src/sprites/info8.png",

    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButton.png",
    PopupBackground: "src/sprites/popupBackground.png",
    messagePopup: "src/sprites/messagePopup.png",
    normalButton: "src/sprites/NormalButton.png",
    bigWinPopup: "src/sprites/BigWinPopup.png",
    hugeWinPopup:"src/sprites/HugeWinPopup.png",
    megaWinPopup: "src/sprites/MegaWinPopup.png",
    jackpotPopup: "src/sprites/jackpotPopup.png",
    freeSpinPopup: "src/sprites/FreeSpinPopup.png",
    leftArrow: "src/sprites/leftArrow.png",
    rightArrow: "src/sprites/RightArrow.png",
    settingText: "src/sprites/SettingText.png",
    crossButton: "src/sprites/crossButton.png",
    crossButtonHover: "src/sprites/crossButtonHover.png",
    infoCross: "src/sprites/infoCross.png",
    disconnectClose: "src/sprites/closeButton.png",

    assetsloader: "src/sprites/assetsloader.png",
    loaderBg: "src/sprites/loaderBg.png",
    reelBg: "src/sprites/reelBg.png",   
    column: "src/sprites/columnLeft.png",
    roof:"src/sprites/Roof.png",
    soundImage:"src/sprites/Sounds.png",
    musicImage: "src/sprites/Music.png",
    headingImage: "src/sprites/PayTable_.png",
    scrollBg: "src/sprites/ScrollBar.png",
    scroller:"src/sprites/Roller.png",
    minorSymbolsHeading: "src/sprites/MoniorSymbols.png",
    majorSymbolHeading: "src/sprites/MajorSymbolsHeading.png",
    specialSymBolHeading: "src/sprites/SpecialSymbolHeading.png",
    yesButton:"src/sprites/yesButton.png",
    yesButtonHover: "src/sprites/yesButtonHover.png",
    noButton:"src/sprites/noButton.png",
    noButtonHover:"src/sprites/noButtonHover.png",
    sounProgress: "src/sprites/soundProgreesBar.png",
    soundPlus: "src/sprites/soundPlus.png",
    soundMinus: "src/sprites/soundMinus.png",
    soundIndicator: "src/sprites/Indicator.png",
    winningBg: "src/sprites/winningBg.png",
    winAmountPanel: "src/sprites/amountPanel.png",
    indicatorSprite: "src/sprites/SliderButton.png",

    left0: "src/sprites/1.png",
    left1: "src/sprites/2.png",
    left2: "src/sprites/3.png",
    left3: "src/sprites/4.png",
    left4: "src/sprites/5.png",
    left5: "src/sprites/6.png",
    left6: "src/sprites/7.png",
    left7: "src/sprites/8.png",
    left8: "src/sprites/9.png",


    leftHover0: "src/sprites/LineNumber1.png",
    leftHover1: "src/sprites/LineNumber2.png",
    leftHover2: "src/sprites/LineNumber3.png",
    leftHover3: "src/sprites/LineNumber4.png",
    leftHover4: "src/sprites/LineNumber5.png",
    leftHover5: "src/sprites/LineNumber6.png",
    leftHover6: "src/sprites/LineNumber7.png",
    leftHover7: "src/sprites/LineNumber8.png",
    leftHover8: "src/sprites/LineNumber9.png",

    right0: "src/sprites/1.png",
    right1: "src/sprites/2.png",
    right2: "src/sprites/3.png",
    right3: "src/sprites/4.png",
    right4: "src/sprites/5.png",
    right5: "src/sprites/6.png",
    right6: "src/sprites/7.png",
    right7: "src/sprites/8.png",
    right8: "src/sprites/9.png",

    rightHover0: "src/sprites/LineNumber1.png",
    rightHover1: "src/sprites/LineNumber2.png",
    rightHover2: "src/sprites/LineNumber3.png",
    rightHover3: "src/sprites/LineNumber4.png",
    rightHover4: "src/sprites/LineNumber5.png",
    rightHover5: "src/sprites/LineNumber6.png",
    rightHover6: "src/sprites/LineNumber7.png",
    rightHover7: "src/sprites/LineNumber8.png",
    rightHover8: "src/sprites/LineNumber9.png",


    line0: "src/sprites/line1.png",
    line1: "src/sprites/line2.png",
    line2: "src/sprites/line3.png",
    line3: "src/sprites/line4.png",
    line4: "src/sprites/line5.png",
    line5: "src/sprites/line6.png",
    line6: "src/sprites/line7.png",
    line7: "src/sprites/line8.png",
    line8: "src/sprites/line9.png",

    Bail0: "src/sprites/Bail1.png",
    Bail1: "src/sprites/Bail2.png",
    Bail2: "src/sprites/Bail3.png",
    Bail3: "src/sprites/Bail4.png",
    Bail4: "src/sprites/Bail5.png",
    Bail5: "src/sprites/Bail6.png",
    Bail6: "src/sprites/Bail7.png",
    Bail7: "src/sprites/Bail8.png",
    Bail8: "src/sprites/Bail9.png",
    Bail9: "src/sprites/Bail10.png",
    Bail10: "src/sprites/Bail11.png",
    Bail11: "src/sprites/Bail12.png",
    Bail12: "src/sprites/Bail13.png",
    Bail13: "src/sprites/Bail14.png",
    Bail14: "src/sprites/Bail15.png",
    Bail15: "src/sprites/Bail16.png",
    Bail16: "src/sprites/Bail17.png",
    Bail17: "src/sprites/Bail18.png",
    Bail18: "src/sprites/Bail19.png",
    Bail19: "src/sprites/Bail20.png",
    Bail20: "src/sprites/Bail21.png",
    Bail21: "src/sprites/Bail22.png",
    Bail22: "src/sprites/Bail23.png",
    Bail23: "src/sprites/Bail24.png",
    Bail24: "src/sprites/Bail5.png",
    Bail25: "src/sprites/Bail26.png",
    Bail26: "src/sprites/Bail27.png",
    Bail27: "src/sprites/Bail28.png",
    Bail28: "src/sprites/Bail29.png",
    Bail29: "src/sprites/Bail30.png",

    coconutButton: "src/sprites/coconutButton.png",

    BackCard1: "src/sprites/Backcard1.png",
    BackCard2: "src/sprites/Backcard2.png",
    BackCard3: "src/sprites/Backcard3.png",
    Double: "src/sprites/withoutName.png",
    collectButton: "src/sprites/CollectButton.png",

    SpadesA:"src/sprites/spadeA.png",
    Spades2: "src/sprites/spade2.png",
    Spades3: "src/sprites/spade3.png",
    Spades4: "src/sprites/spade4.png",
    Spades5: "src/sprites/spade5.png",
    Spades6: "src/sprites/spade6.png",
    Spades7: "src/sprites/spade7.png",
    Spades8: "src/sprites/spade8.png",
    Spades9: "src/sprites/spade9.png",
    Spades10: "src/sprites/spade10.png",
    SpadesJ: "src/sprites/spadeJ.png",
    SpadesQ: "src/sprites/spadeQ.png",
    SpadesK: "src/sprites/spadeK.png",

    HeartsA: "src/sprites/HeartA.png",
    Hearts2: "src/sprites/Heart2.png",
    Hearts3: "src/sprites/Heart3.png",
    Hearts4: "src/sprites/Heart4.png",
    Hearts5: "src/sprites/Heart5.png",
    Hearts6: "src/sprites/Heart6.png",
    Hearts7: "src/sprites/Heart7.png",
    Hearts8: "src/sprites/Heart8.png",
    Hearts9: "src/sprites/Heart9.png",
    Hearts10: "src/sprites/Heart10.png",
    HeartsJ: "src/sprites/HeartJ.png",
    HeartsQ: "src/sprites/HeartQ.png",
    HeartsK: "src/sprites/HeartK.png",

    ClubsA: "src/sprites/ClubA.png",
    Clubs2: "src/sprites/Club2.png",
    Clubs3: "src/sprites/Club3.png",
    Clubs4: "src/sprites/Club4.png",
    Clubs5: "src/sprites/Club5.png",
    Clubs6: "src/sprites/Club6.png",
    Clubs7: "src/sprites/Club7.png",
    Clubs8: "src/sprites/Club8.png",
    Clubs9: "src/sprites/Club9.png",
    Clubs10: "src/sprites/Club10.png",
    ClubsJ: "src/sprites/ClubJ.png",
    ClubsQ: "src/sprites/ClubQ.png",
    ClubsK: "src/sprites/ClubK.png",

    DiamondsA: "src/sprites/DiamondA.png",
    Diamonds2: "src/sprites/Diamond2.png",
    Diamonds3: "src/sprites/Diamond3.png",
    Diamonds4: "src/sprites/Diamond4.png",
    Diamonds5: "src/sprites/Diamond5.png",
    Diamonds6: "src/sprites/Diamond6.png",
    Diamonds7: "src/sprites/Diamond7.png",
    Diamonds8: "src/sprites/Diamond8.png",
    Diamonds9: "src/sprites/Diamond9.png",
    Diamonds10: "src/sprites/Diamond10.png",
    DiamondsJ: "src/sprites/DiamondJ.png",
    DiamondsQ: "src/sprites/DiamondQ.png",
    DiamondsK: "src/sprites/DiamondK.png",

    coconutAnim0: "src/sprites/coconutanim1.png",
    coconutAnim1: "src/sprites/coconutanim2.png",
    coconutAnim2: "src/sprites/coconutanim3.png",
    coconutAnim3: "src/sprites/coconutanim4.png",
    coconutAnim4: "src/sprites/coconutanim5.png",
    coconutAnim5: "src/sprites/coconutanim6.png",
    coconutAnim6: "src/sprites/coconutanim7.png",
    coconutAnim7: "src/sprites/coconutanim8.png",
    coconutAnim8: "src/sprites/coconutanim9.png",
    coconutAnim9: "src/sprites/coconutanim10.png",
    coconutAnim10: "src/sprites/coconutanim11.png",
    coconutAnim11: "src/sprites/coconutanim12.png",
    coconutAnim12: "src/sprites/coconutanim13.png",
    coconutAnim13: "src/sprites/coconutanim14.png",
    coconutAnim14: "src/sprites/coconutanim15.png",
    coconutAnim15: "src/sprites/coconutanim16.png",
    coconutAnim16: "src/sprites/coconutanim17.png",
    coconutAnim17: "src/sprites/coconutanim18.png",
    coconutAnim18: "src/sprites/coconutanim19.png",
    coconutAnim19: "src/sprites/coconutanim20.png",
    coconutAnim20: "src/sprites/coconutanim21.png",
    coconutAnim21: "src/sprites/coconutanim22.png",
    coconutAnim22: "src/sprites/coconutanim23.png",
    coconutAnim23: "src/sprites/coconutanim24.png",
    coconutAnim24: "src/sprites/coconutanim25.png",
    coconutAnim25: "src/sprites/coconutanim26.png",
    coconutAnim26: "src/sprites/coconutanim27.png",
    coconutAnim27: "src/sprites/coconutanim28.png",
    coconutAnim28: "src/sprites/coconutanim29.png",
    coconutAnim29: "src/sprites/coconutanim30.png",
    coconutAnim30: "src/sprites/coconutanim31.png",
    coconutAnim31: "src/sprites/coconutanim32.png",
    coconutAnim32: "src/sprites/coconutanim33.png",
    coconutAnim33: "src/sprites/coconutanim34.png",
    coconutAnim34: "src/sprites/coconutanim35.png",
    coconutAnim35: "src/sprites/coconutanim36.png",
    coconutAnim36: "src/sprites/coconutanim37.png",
    coconutAnim37: "src/sprites/coconutanim38.png",
    coconutAnim38: "src/sprites/coconutanim39.png",
    coconutAnim39: "src/sprites/coconutanim40.png",
    coconutAnim40: "src/sprites/coconutanim41.png",
    coconutAnim41: "src/sprites/coconutanim42.png",
    coconutAnim42: "src/sprites/coconutanim43.png",
    coconutAnim43: "src/sprites/coconutanim44.png",
    coconutAnim44: "src/sprites/coconutanim45.png",
    coconutAnim45: "src/sprites/coconutanim46.png",
    coconutAnim46: "src/sprites/coconutanim47.png",
    coconutAnim47: "src/sprites/coconutanim48.png",

    slots0_0 :  "/src/sprites/Symbols/icon1/icon1.png",
   
    slots1_0 :  "/src/sprites/Symbols/icon2/icon1.png",

    slots2_0 :  "/src/sprites/Symbols/icon3/Icon_3.png",
    
    slots3_0 :  "/src/sprites/Symbols/icon4/icon_4.png",
   
    slots4_0 :  "/src/sprites/Symbols/icon5/icon_5.png",
   
    slots5_0 :  "/src/sprites/Symbols/icon6/icon_6.png",
   
    slots6_0 :  "/src/sprites/Symbols/icon7/icon_7.png",
  
    slots7_0 :  "/src/sprites/Symbols/icon8/icon_8.png",
    slots8_0 :  "/src/sprites/Symbols/icon9/Bonus.png",


    man0: "src/sprites/man0.png",
    man1: "src/sprites/man1.png",
    man2: "src/sprites/man2.png",
    man3: "src/sprites/man3.png",
    man4: "src/sprites/man4.png",
    man5: "src/sprites/man5.png",
    man6: "src/sprites/man6.png",
    man7: "src/sprites/man7.png",
    man8: "src/sprites/man8.png",
    man9: "src/sprites/man9.png",
    man10: "src/sprites/man10.png",
    man11: "src/sprites/man11.png",
    man12: "src/sprites/man12.png",
    man13: "src/sprites/man13.png",
    man14: "src/sprites/man14.png",
    man15: "src/sprites/man15.png",
    man16: "src/sprites/man16.png",
    man17: "src/sprites/man17.png",
    man18: "src/sprites/man18.png",
    man19: "src/sprites/man19.png",
    man20: "src/sprites/man20.png",
    man21: "src/sprites/man21.png",
    man22: "src/sprites/man22.png",
    man23: "src/sprites/man23.png",
    man24: "src/sprites/man24.png",
    man25: "src/sprites/man25.png",
    man26: "src/sprites/man26.png",
    man27: "src/sprites/man27.png",
    man28: "src/sprites/man28.png",
    man29: "src/sprites/man29.png",
    man30: "src/sprites/man30.png",
    man31: "src/sprites/man31.png",
    man32: "src/sprites/man32.png",
    man33: "src/sprites/man33.png",
}



export const staticData = {
    Background:  "src/sprites/Background.jpg",
};

export const fontData = {
    crashLandingItalic : "src/fonts/CrashLandingBB.ttf"
}



export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/Teaser.mp3",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/spin.wav",
        winMusic: "src/sounds/JackpotWinner.mp3",
        buttonpressed: "src/sounds/Game-Button.mp3",
        spinWheelMusic: "src/sounds/spinWheel.mp3",
        bonusBg: "src/sounds/bonusbg.wav",
        bonuswin: "src/sounds/bonuswin.wav",
        cardMusic: "src/sounds/card.mp3",
        coconutFall: "src/sounds/coconutfall.wav"
 
};

export const preloaderConfig = {
    // startLogo:  "/src/sprites/Logo.png")
}