import { disconnect } from "process";

// import { Background } from './Background';
export const LoaderConfig = {
    // frame : "/src/sprites/SlotMachine_3x5.png",
    Background: "src/sprites/Background.jpg",
    gameBg: "src/sprites/Background.jpg",
    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",
    maxBetBtn :  "/src/sprites/ButtonMaxBet_1.png",
    maxBetBtOnPressed :  "/src/sprites/ButtonMaxBetHover_1.png",
    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed : "/src/sprites/ButtonAutoSpinHover_1.png",
    BetPanel :  "/src/sprites/PanelTotalBet.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    mBtn  :  "/src/sprites/ButtonMinus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    mBtnH  :  "/src/sprites/ButtonMinusHover.png",
    lines :  "/src/sprites/PanelLines.png",
    winPanel :  "/src/sprites/PanelWin.png",
    winPanel1:  "/src/sprites/PanelWin1.png",        
    balancePanel :  "/src/sprites/PanelBalance.png",
    doubleButton: "src/sprites/doubleButton.png",
    doubleButtonPressed : "src/sprites/doubleButtonPressed.png",
    winBg: "src/sprites/winBg.png",
    MenuBtn :  "/src/sprites/ButtonMenu.png",
    MenuBtnH :  "/src/sprites/ButtonMenuHover.png",
    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png",
    linesNumber: "src/sprites/LinesNumber.png",

    inofIcon1: "src/sprites/info1.png",
    inofIcon2: "src/sprites/info2.png",
    inofIcon3: "src/sprites/info3.png",
    inofIcon4: "src/sprites/info4.png",
    inofIcon5: "src/sprites/info5.png",
    inofIcon6: "src/sprites/info6.png",
    inofIcon7: "src/sprites/info7.png",
    inofIcon8: "src/sprites/info8.png",

    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButton.png",
    PopupBackground: "src/sprites/popupBackground.png",
    messagePopup: "src/sprites/messagePopup.png",
    normalButton: "src/sprites/NormalButton.png",
    bigWinPopup: "src/sprites/BigWinPopup.png",
    hugeWinPopup:"src/sprites/HugeWinPopup.png",
    megaWinPopup: "src/sprites/MegaWinPopup.png",
    jackpotPopup: "src/sprites/jackpotPopup.png",
    freeSpinPopup: "src/sprites/FreeSpinPopup.png",
    leftArrow: "src/sprites/leftArrow.png",
    rightArrow: "src/sprites/RightArrow.png",
    settingText: "src/sprites/SettingText.png",
    crossButton: "src/sprites/crossButton.png",
    crossButtonHover: "src/sprites/crossButtonHover.png",
    infoCross: "src/sprites/infoCross.png",
    disconnectClose: "src/sprites/closeButton.png",

    assetsloader: "src/sprites/assetsloader.png",
    loaderBg: "src/sprites/loaderBg.png",
    reelBg: "src/sprites/reelBg.png",   
    column: "src/sprites/columnLeft.png",
    roof:"src/sprites/Roof.png",
    soundImage:"src/sprites/Sounds.png",
    musicImage: "src/sprites/Music.png",
    headingImage: "src/sprites/PayTable_.png",
    scrollBg: "src/sprites/ScrollBar.png",
    scroller:"src/sprites/Roller.png",
    minorSymbolsHeading: "src/sprites/MoniorSymbols.png",
    majorSymbolHeading: "src/sprites/MajorSymbolsHeading.png",
    specialSymBolHeading: "src/sprites/SpecialSymbolHeading.png",
    yesButton:"src/sprites/yesButton.png",
    yesButtonHover: "src/sprites/yesButtonHover.png",
    noButton:"src/sprites/noButton.png",
    noButtonHover:"src/sprites/noButtonHover.png",
    sounProgress: "src/sprites/soundProgreesBar.png",
    soundPlus: "src/sprites/soundPlus.png",
    soundMinus: "src/sprites/soundMinus.png",
    soundIndicator: "src/sprites/Indicator.png",
    winningBg: "src/sprites/winningBg.png",
    winAmountPanel: "src/sprites/amountPanel.png",
    indicatorSprite: "src/sprites/SliderButton.png",

    left0: "src/sprites/1.png",
    left1: "src/sprites/2.png",
    left2: "src/sprites/3.png",
    left3: "src/sprites/4.png",
    left4: "src/sprites/5.png",
    left5: "src/sprites/6.png",
    left6: "src/sprites/7.png",
    left7: "src/sprites/8.png",
    left8: "src/sprites/9.png",


    leftHover0: "src/sprites/LineNumber1.png",
    leftHover1: "src/sprites/LineNumber2.png",
    leftHover2: "src/sprites/LineNumber3.png",
    leftHover3: "src/sprites/LineNumber4.png",
    leftHover4: "src/sprites/LineNumber5.png",
    leftHover5: "src/sprites/LineNumber6.png",
    leftHover6: "src/sprites/LineNumber7.png",
    leftHover7: "src/sprites/LineNumber8.png",
    leftHover8: "src/sprites/LineNumber9.png",

    right0: "src/sprites/1.png",
    right1: "src/sprites/2.png",
    right2: "src/sprites/3.png",
    right3: "src/sprites/4.png",
    right4: "src/sprites/5.png",
    right5: "src/sprites/6.png",
    right6: "src/sprites/7.png",
    right7: "src/sprites/8.png",
    right8: "src/sprites/9.png",

    rightHover0: "src/sprites/LineNumber1.png",
    rightHover1: "src/sprites/LineNumber2.png",
    rightHover2: "src/sprites/LineNumber3.png",
    rightHover3: "src/sprites/LineNumber4.png",
    rightHover4: "src/sprites/LineNumber5.png",
    rightHover5: "src/sprites/LineNumber6.png",
    rightHover6: "src/sprites/LineNumber7.png",
    rightHover7: "src/sprites/LineNumber8.png",
    rightHover8: "src/sprites/LineNumber9.png",


    line0: "src/sprites/line1.png",
    line1: "src/sprites/line2.png",
    line2: "src/sprites/line3.png",
    line3: "src/sprites/line4.png",
    line4: "src/sprites/line5.png",
    line5: "src/sprites/line6.png",
    line6: "src/sprites/line7.png",
    line7: "src/sprites/line8.png",
    line8: "src/sprites/line9.png",

    Bail0: "src/sprites/Bail1.png",
    Bail1: "src/sprites/Bail2.png",
    Bail2: "src/sprites/Bail3.png",
    Bail3: "src/sprites/Bail4.png",
    Bail4: "src/sprites/Bail5.png",
    Bail5: "src/sprites/Bail6.png",
    Bail6: "src/sprites/Bail7.png",
    Bail7: "src/sprites/Bail8.png",
    Bail8: "src/sprites/Bail9.png",
    Bail9: "src/sprites/Bail10.png",
    Bail10: "src/sprites/Bail11.png",
    Bail11: "src/sprites/Bail12.png",
    Bail12: "src/sprites/Bail13.png",
    Bail13: "src/sprites/Bail14.png",
    Bail14: "src/sprites/Bail15.png",
    Bail15: "src/sprites/Bail16.png",
    Bail16: "src/sprites/Bail17.png",
    Bail17: "src/sprites/Bail18.png",
    Bail18: "src/sprites/Bail19.png",
    Bail19: "src/sprites/Bail20.png",
    Bail20: "src/sprites/Bail21.png",
    Bail21: "src/sprites/Bail22.png",
    Bail22: "src/sprites/Bail23.png",
    Bail23: "src/sprites/Bail24.png",
    Bail24: "src/sprites/Bail5.png",
    Bail25: "src/sprites/Bail26.png",
    Bail26: "src/sprites/Bail27.png",
    Bail27: "src/sprites/Bail28.png",
    Bail28: "src/sprites/Bail29.png",
    Bail29: "src/sprites/Bail30.png",

    coconutButton: "src/sprites/coconutButton.png",

    BackCard1: "src/sprites/Backcard1.png",
    BackCard2: "src/sprites/Backcard2.png",
    BackCard3: "src/sprites/Backcard3.png",
    Double: "src/sprites/withoutName.png",
    collectButton: "src/sprites/CollectButton.png",

    SpadesA:"src/sprites/spadeA.png",
    Spades2: "src/sprites/spade2.png",
    Spades3: "src/sprites/spade3.png",
    Spades4: "src/sprites/spade4.png",
    Spades5: "src/sprites/spade5.png",
    Spades6: "src/sprites/spade6.png",
    Spades7: "src/sprites/spade7.png",
    Spades8: "src/sprites/spade8.png",
    Spades9: "src/sprites/spade9.png",
    Spades10: "src/sprites/spade10.png",
    SpadesJ: "src/sprites/spadeJ.png",
    SpadesQ: "src/sprites/spadeQ.png",
    SpadesK: "src/sprites/spadeK.png",

    HeartsA: "src/sprites/HeartA.png",
    Hearts2: "src/sprites/Heart2.png",
    Hearts3: "src/sprites/Heart3.png",
    Hearts4: "src/sprites/Heart4.png",
    Hearts5: "src/sprites/Heart5.png",
    Hearts6: "src/sprites/Heart6.png",
    Hearts7: "src/sprites/Heart7.png",
    Hearts8: "src/sprites/Heart8.png",
    Hearts9: "src/sprites/Heart9.png",
    Hearts10: "src/sprites/Heart10.png",
    HeartsJ: "src/sprites/HeartJ.png",
    HeartsQ: "src/sprites/HeartQ.png",
    HeartsK: "src/sprites/HeartK.png",

    ClubsA: "src/sprites/ClubA.png",
    Clubs2: "src/sprites/Club2.png",
    Clubs3: "src/sprites/Club3.png",
    Clubs4: "src/sprites/Club4.png",
    Clubs5: "src/sprites/Club5.png",
    Clubs6: "src/sprites/Club6.png",
    Clubs7: "src/sprites/Club7.png",
    Clubs8: "src/sprites/Club8.png",
    Clubs9: "src/sprites/Club9.png",
    Clubs10: "src/sprites/Club10.png",
    ClubsJ: "src/sprites/ClubJ.png",
    ClubsQ: "src/sprites/ClubQ.png",
    ClubsK: "src/sprites/ClubK.png",

    DiamondsA: "src/sprites/DiamondA.png",
    Diamonds2: "src/sprites/Diamond2.png",
    Diamonds3: "src/sprites/Diamond3.png",
    Diamonds4: "src/sprites/Diamond4.png",
    Diamonds5: "src/sprites/Diamond5.png",
    Diamonds6: "src/sprites/Diamond6.png",
    Diamonds7: "src/sprites/Diamond7.png",
    Diamonds8: "src/sprites/Diamond8.png",
    Diamonds9: "src/sprites/Diamond9.png",
    Diamonds10: "src/sprites/Diamond10.png",
    DiamondsJ: "src/sprites/DiamondJ.png",
    DiamondsQ: "src/sprites/DiamondQ.png",
    DiamondsK: "src/sprites/DiamondK.png",

    coconutAnim0: "src/sprites/coconutanim1.png",
    coconutAnim1: "src/sprites/coconutanim2.png",
    coconutAnim2: "src/sprites/coconutanim3.png",
    coconutAnim3: "src/sprites/coconutanim4.png",
    coconutAnim4: "src/sprites/coconutanim5.png",
    coconutAnim5: "src/sprites/coconutanim6.png",
    coconutAnim6: "src/sprites/coconutanim7.png",
    coconutAnim7: "src/sprites/coconutanim8.png",
    coconutAnim8: "src/sprites/coconutanim9.png",
    coconutAnim9: "src/sprites/coconutanim10.png",
    coconutAnim10: "src/sprites/coconutanim11.png",
    coconutAnim11: "src/sprites/coconutanim12.png",
    coconutAnim12: "src/sprites/coconutanim13.png",
    coconutAnim13: "src/sprites/coconutanim14.png",
    coconutAnim14: "src/sprites/coconutanim15.png",
    coconutAnim15: "src/sprites/coconutanim16.png",
    coconutAnim16: "src/sprites/coconutanim17.png",
    coconutAnim17: "src/sprites/coconutanim18.png",
    coconutAnim18: "src/sprites/coconutanim19.png",
    coconutAnim19: "src/sprites/coconutanim20.png",
    coconutAnim20: "src/sprites/coconutanim21.png",
    coconutAnim21: "src/sprites/coconutanim22.png",
    coconutAnim22: "src/sprites/coconutanim23.png",
    coconutAnim23: "src/sprites/coconutanim24.png",
    coconutAnim24: "src/sprites/coconutanim25.png",
    coconutAnim25: "src/sprites/coconutanim26.png",
    coconutAnim26: "src/sprites/coconutanim27.png",
    coconutAnim27: "src/sprites/coconutanim28.png",
    coconutAnim28: "src/sprites/coconutanim29.png",
    coconutAnim29: "src/sprites/coconutanim30.png",
    coconutAnim30: "src/sprites/coconutanim31.png",
    coconutAnim31: "src/sprites/coconutanim32.png",
    coconutAnim32: "src/sprites/coconutanim33.png",
    coconutAnim33: "src/sprites/coconutanim34.png",
    coconutAnim34: "src/sprites/coconutanim35.png",
    coconutAnim35: "src/sprites/coconutanim36.png",
    coconutAnim36: "src/sprites/coconutanim37.png",
    coconutAnim37: "src/sprites/coconutanim38.png",
    coconutAnim38: "src/sprites/coconutanim39.png",
    coconutAnim39: "src/sprites/coconutanim40.png",
    coconutAnim40: "src/sprites/coconutanim41.png",
    coconutAnim41: "src/sprites/coconutanim42.png",
    coconutAnim42: "src/sprites/coconutanim43.png",
    coconutAnim43: "src/sprites/coconutanim44.png",
    coconutAnim44: "src/sprites/coconutanim45.png",
    coconutAnim45: "src/sprites/coconutanim46.png",
    coconutAnim46: "src/sprites/coconutanim47.png",
    coconutAnim47: "src/sprites/coconutanim48.png",

    slots0_0 :  "/src/sprites/Symbols/icon1/icon1.png",
   
    slots1_0 :  "/src/sprites/Symbols/icon2/icon1.png",

    slots2_0 :  "/src/sprites/Symbols/icon3/Icon_3.png",
    
    slots3_0 :  "/src/sprites/Symbols/icon4/icon_4.png",
   
    slots4_0 :  "/src/sprites/Symbols/icon5/icon_5.png",
   
    slots5_0 :  "/src/sprites/Symbols/icon6/icon_6.png",
   
    slots6_0 :  "/src/sprites/Symbols/icon7/icon_7.png",
  
    slots7_0 :  "/src/sprites/Symbols/icon8/icon_8.png",
    slots8_0 :  "/src/sprites/Symbols/icon9/Bonus.png",


    man0: "src/sprites/man0.png",
    man1: "src/sprites/man1.png",
    man2: "src/sprites/man2.png",
    man3: "src/sprites/man3.png",
    man4: "src/sprites/man4.png",
    man5: "src/sprites/man5.png",
    man6: "src/sprites/man6.png",
    man7: "src/sprites/man7.png",
    man8: "src/sprites/man8.png",
    man9: "src/sprites/man9.png",
    man10: "src/sprites/man10.png",
    man11: "src/sprites/man11.png",
    man12: "src/sprites/man12.png",
    man13: "src/sprites/man13.png",
    man14: "src/sprites/man14.png",
    man15: "src/sprites/man15.png",
    man16: "src/sprites/man16.png",
    man17: "src/sprites/man17.png",
    man18: "src/sprites/man18.png",
    man19: "src/sprites/man19.png",
    man20: "src/sprites/man20.png",
    man21: "src/sprites/man21.png",
    man22: "src/sprites/man22.png",
    man23: "src/sprites/man23.png",
    man24: "src/sprites/man24.png",
    man25: "src/sprites/man25.png",
    man26: "src/sprites/man26.png",
    man27: "src/sprites/man27.png",
    man28: "src/sprites/man28.png",
    man29: "src/sprites/man29.png",
    man30: "src/sprites/man30.png",
    man31: "src/sprites/man31.png",
    man32: "src/sprites/man32.png",
    man33: "src/sprites/man33.png",

    // slots9_0 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 01.png",
    // slots9_1 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 02.png",
    // slots9_2 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 03.png",
    // slots9_3 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 04.png",
    // slots9_4 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 05.png",
    // slots9_5 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 06.png",
    // slots9_6 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 07.png",
    // slots9_7 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 08.png",
    // slots9_8 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 09.png",
    // slots9_9 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 10.png",
    // slots9_10:  "/src/sprites/Symbols/FreeSpins/FreeSpins 11.png",
    // slots9_11:  "/src/sprites/Symbols/FreeSpins/FreeSpins 12.png",
    // slots9_12:  "/src/sprites/Symbols/FreeSpins/FreeSpins 13.png",
    // slots9_13:  "/src/sprites/Symbols/FreeSpins/FreeSpins 14.png",
    // slots9_14:  "/src/sprites/Symbols/FreeSpins/FreeSpins 15.png",
    // slots9_15:  "/src/sprites/Symbols/FreeSpins/FreeSpins 16.png",
    // slots9_16:  "/src/sprites/Symbols/FreeSpins/FreeSpins 17.png",
    // slots9_17:  "/src/sprites/Symbols/FreeSpins/FreeSpins 18.png",
    // slots9_18:  "/src/sprites/Symbols/FreeSpins/FreeSpins 19.png",
    // slots9_19:  "/src/sprites/Symbols/FreeSpins/FreeSpins 20.png",
    // slots9_20:  "/src/sprites/Symbols/FreeSpins/FreeSpins 21.png",
    // slots9_21:  "/src/sprites/Symbols/FreeSpins/FreeSpins 22.png",
    // slots9_22:  "/src/sprites/Symbols/FreeSpins/FreeSpins 23.png",
    // slots9_23:  "/src/sprites/Symbols/FreeSpins/FreeSpins 24.png",
    // slots9_24:  "/src/sprites/Symbols/FreeSpins/FreeSpins 25.png",
    // slots9_25:  "/src/sprites/Symbols/FreeSpins/FreeSpins 26.png",
    // slots9_26:  "/src/sprites/Symbols/FreeSpins/FreeSpins 27.png",
    // slots9_27:  "/src/sprites/Symbols/FreeSpins/FreeSpins 28.png",
    // slots9_28:  "/src/sprites/Symbols/FreeSpins/FreeSpins 29.png",
    // slots9_29:  "/src/sprites/Symbols/FreeSpins/FreeSpins 30.png",
    // slots9_30:  "/src/sprites/Symbols/FreeSpins/FreeSpins 31.png",
    // slots9_31:  "/src/sprites/Symbols/FreeSpins/FreeSpins 32.png",
    // slots9_32:  "/src/sprites/Symbols/FreeSpins/FreeSpins 33.png",
    // slots9_33:  "/src/sprites/Symbols/FreeSpins/FreeSpins 34.png",
    // slots9_34:  "/src/sprites/Symbols/FreeSpins/FreeSpins 35.png",
    // slots9_35:  "/src/sprites/Symbols/FreeSpins/FreeSpins 36.png",


    // slots10_0 :  "/src/sprites/Symbols/Wild/Wild 01.png",
    // slots10_1 :  "/src/sprites/Symbols/Wild/Wild 02.png",
    // slots10_2 :  "/src/sprites/Symbols/Wild/Wild 03.png",
    // slots10_3 :  "/src/sprites/Symbols/Wild/Wild 04.png",
    // slots10_4 :  "/src/sprites/Symbols/Wild/Wild 05.png",
    // slots10_5 :  "/src/sprites/Symbols/Wild/Wild 06.png",
    // slots10_6 :  "/src/sprites/Symbols/Wild/Wild 07.png",
    // slots10_7 :  "/src/sprites/Symbols/Wild/Wild 08.png",
    // slots10_8 :  "/src/sprites/Symbols/Wild/Wild 09.png",
    // slots10_9 :  "/src/sprites/Symbols/Wild/Wild 10.png",
    // slots10_10:  "/src/sprites/Symbols/Wild/Wild 11.png",
    // slots10_11:  "/src/sprites/Symbols/Wild/Wild 12.png",
    // slots10_12:  "/src/sprites/Symbols/Wild/Wild 13.png",
    // slots10_13:  "/src/sprites/Symbols/Wild/Wild 14.png",
    // slots10_14:  "/src/sprites/Symbols/Wild/Wild 15.png",
    // slots10_15:  "/src/sprites/Symbols/Wild/Wild 16.png",
    // slots10_16:  "/src/sprites/Symbols/Wild/Wild 17.png",
    // slots10_17:  "/src/sprites/Symbols/Wild/Wild 18.png",
    // slots10_18:  "/src/sprites/Symbols/Wild/Wild 19.png",
    // slots10_19:  "/src/sprites/Symbols/Wild/Wild 20.png",
    // slots10_20:  "/src/sprites/Symbols/Wild/Wild 21.png",
    // slots10_21:  "/src/sprites/Symbols/Wild/Wild 22.png",
    // slots10_22:  "/src/sprites/Symbols/Wild/Wild 23.png",
    // slots10_23:  "/src/sprites/Symbols/Wild/Wild 24.png",
    // slots10_24:  "/src/sprites/Symbols/Wild/Wild 25.png",
    // slots10_25:  "/src/sprites/Symbols/Wild/Wild 26.png",
    // slots10_26:  "/src/sprites/Symbols/Wild/Wild 27.png",
    // slots10_27:  "/src/sprites/Symbols/Wild/Wild 28.png",
    // slots10_28:  "/src/sprites/Symbols/Wild/Wild 29.png",
    // slots10_29:  "/src/sprites/Symbols/Wild/Wild 30.png",
    // slots10_30:  "/src/sprites/Symbols/Wild/Wild 31.png",
    // slots10_31:  "/src/sprites/Symbols/Wild/Wild 32.png",
    // slots10_32:  "/src/sprites/Symbols/Wild/Wild 33.png",
    // slots10_33:  "/src/sprites/Symbols/Wild/Wild 34.png",
    // slots10_34:  "/src/sprites/Symbols/Wild/Wild 35.png",
    // slots10_35:  "/src/sprites/Symbols/Wild/Wild 36.png",

    // slots9_0 :  "/src/sprites/Symbols/Wick/Wick (1).png",
    // slots9_1 :  "/src/sprites/Symbols/Wick/Wick (2).png",
    // slots9_2 :  "/src/sprites/Symbols/Wick/Wick (3).png",
    // slots9_3 :  "/src/sprites/Symbols/Wick/Wick (4).png",
    // slots9_4 :  "/src/sprites/Symbols/Wick/Wick (5).png",
    // slots9_5 :  "/src/sprites/Symbols/Wick/Wick (6).png",
    // slots9_6 :  "/src/sprites/Symbols/Wick/Wick (7).png",
    // slots9_7 :  "/src/sprites/Symbols/Wick/Wick (8).png",
    // slots9_8 :  "/src/sprites/Symbols/Wick/Wick (9).png",
    // slots9_9 :  "/src/sprites/Symbols/Wick/Wick (10).png",
    // slots9_10:  "/src/sprites/Symbols/Wick/Wick (11).png",
    // slots9_11:  "/src/sprites/Symbols/Wick/Wick (12).png",
    // slots9_12:  "/src/sprites/Symbols/Wick/Wick (13).png",
    // slots9_13:  "/src/sprites/Symbols/Wick/Wick (14).png",
    // slots9_14:  "/src/sprites/Symbols/Wick/Wick (15).png",
    // slots9_15:  "/src/sprites/Symbols/Wick/Wick (16).png",
    // slots9_16:  "/src/sprites/Symbols/Wick/Wick (17).png",
    // slots9_17:  "/src/sprites/Symbols/Wick/Wick (18).png",
    // slots9_18:  "/src/sprites/Symbols/Wick/Wick (19).png",
    // slots9_19:  "/src/sprites/Symbols/Wick/Wick (20).png",
    // slots9_20:  "/src/sprites/Symbols/Wick/Wick (21).png",
    // slots9_21:  "/src/sprites/Symbols/Wick/Wick (22).png",
    // slots9_22:  "/src/sprites/Symbols/Wick/Wick (23).png",
    // slots9_23:  "/src/sprites/Symbols/Wick/Wick (24).png",

    // slots11_0 :  "/src/sprites/Symbols/Scatter/Scatter 01.png",
    // slots11_1 :  "/src/sprites/Symbols/Scatter/Scatter 02.png",
    // slots11_2 :  "/src/sprites/Symbols/Scatter/Scatter 03.png",
    // slots11_3 :  "/src/sprites/Symbols/Scatter/Scatter 04.png",
    // slots11_4 :  "/src/sprites/Symbols/Scatter/Scatter 05.png",
    // slots11_5 :  "/src/sprites/Symbols/Scatter/Scatter 06.png",
    // slots11_6 :  "/src/sprites/Symbols/Scatter/Scatter 07.png",
    // slots11_7 :  "/src/sprites/Symbols/Scatter/Scatter 08.png",
    // slots11_8 :  "/src/sprites/Symbols/Scatter/Scatter 09.png",
    // slots11_9 :  "/src/sprites/Symbols/Scatter/Scatter 10.png",
    // slots11_10:  "/src/sprites/Symbols/Scatter/Scatter 11.png",
    // slots11_11:  "/src/sprites/Symbols/Scatter/Scatter 12.png",
    // slots11_12:  "/src/sprites/Symbols/Scatter/Scatter 13.png",
    // slots11_13:  "/src/sprites/Symbols/Scatter/Scatter 14.png",
    // slots11_14:  "/src/sprites/Symbols/Scatter/Scatter 15.png",
    // slots11_15:  "/src/sprites/Symbols/Scatter/Scatter 16.png",
    // slots11_16:  "/src/sprites/Symbols/Scatter/Scatter 17.png",
    // slots11_17:  "/src/sprites/Symbols/Scatter/Scatter 18.png",
    // slots11_18:  "/src/sprites/Symbols/Scatter/Scatter 19.png",
    // slots11_19:  "/src/sprites/Symbols/Scatter/Scatter 20.png",
    // slots11_20:  "/src/sprites/Symbols/Scatter/Scatter 21.png",
    // slots11_21:  "/src/sprites/Symbols/Scatter/Scatter 22.png",
    // slots11_22:  "/src/sprites/Symbols/Scatter/Scatter 23.png",
    // slots11_23:  "/src/sprites/Symbols/Scatter/Scatter 24.png",
    // slots11_24:  "/src/sprites/Symbols/Scatter/Scatter 25.png",
    // slots11_25:  "/src/sprites/Symbols/Scatter/Scatter 26.png",
    // slots11_26:  "/src/sprites/Symbols/Scatter/Scatter 27.png",
    // slots11_27:  "/src/sprites/Symbols/Scatter/Scatter 28.png",
    // slots11_28:  "/src/sprites/Symbols/Scatter/Scatter 29.png",
    // slots11_29:  "/src/sprites/Symbols/Scatter/Scatter 30.png",
    // slots11_30:  "/src/sprites/Symbols/Scatter/Scatter 31.png",
    // slots11_31:  "/src/sprites/Symbols/Scatter/Scatter 32.png",
    // slots11_32:  "/src/sprites/Symbols/Scatter/Scatter 33.png",
    // slots11_33:  "/src/sprites/Symbols/Scatter/Scatter 34.png",
    // slots11_34:  "/src/sprites/Symbols/Scatter/Scatter 35.png",
    // slots11_35:  "/src/sprites/Symbols/Scatter/Scatter 36.png",   

    // slots12_0 :  "/src/sprites/Symbols/Jackpot/Jackpot 01.png",
    // slots12_1 :  "/src/sprites/Symbols/Jackpot/Jackpot 02.png",
    // slots12_2 :  "/src/sprites/Symbols/Jackpot/Jackpot 03.png",
    // slots12_3 :  "/src/sprites/Symbols/Jackpot/Jackpot 04.png",
    // slots12_4 :  "/src/sprites/Symbols/Jackpot/Jackpot 05.png",
    // slots12_5 :  "/src/sprites/Symbols/Jackpot/Jackpot 06.png",
    // slots12_6 :  "/src/sprites/Symbols/Jackpot/Jackpot 07.png",
    // slots12_7 :  "/src/sprites/Symbols/Jackpot/Jackpot 08.png",
    // slots12_8 :  "/src/sprites/Symbols/Jackpot/Jackpot 09.png",
    // slots12_9 :  "/src/sprites/Symbols/Jackpot/Jackpot 10.png",
    // slots12_10:  "/src/sprites/Symbols/Jackpot/Jackpot 11.png",
    // slots12_11:  "/src/sprites/Symbols/Jackpot/Jackpot 12.png",
    // slots12_12:  "/src/sprites/Symbols/Jackpot/Jackpot 13.png",
    // slots12_13:  "/src/sprites/Symbols/Jackpot/Jackpot 14.png",
    // slots12_14:  "/src/sprites/Symbols/Jackpot/Jackpot 15.png",
    // slots12_15:  "/src/sprites/Symbols/Jackpot/Jackpot 16.png",
    // slots12_16:  "/src/sprites/Symbols/Jackpot/Jackpot 17.png",
    // slots12_17:  "/src/sprites/Symbols/Jackpot/Jackpot 18.png",
    // slots12_18:  "/src/sprites/Symbols/Jackpot/Jackpot 19.png",
    // slots12_19:  "/src/sprites/Symbols/Jackpot/Jackpot 20.png",
    // slots12_20:  "/src/sprites/Symbols/Jackpot/Jackpot 21.png",
    // slots12_21:  "/src/sprites/Symbols/Jackpot/Jackpot 22.png",
    // slots12_22:  "/src/sprites/Symbols/Jackpot/Jackpot 23.png",
    // slots12_23:  "/src/sprites/Symbols/Jackpot/Jackpot 24.png",
    // slots12_24:  "/src/sprites/Symbols/Jackpot/Jackpot 25.png",
    // slots12_25:  "/src/sprites/Symbols/Jackpot/Jackpot 26.png",
    // slots12_26:  "/src/sprites/Symbols/Jackpot/Jackpot 27.png",
    // slots12_27:  "/src/sprites/Symbols/Jackpot/Jackpot 28.png",
    // slots12_28:  "/src/sprites/Symbols/Jackpot/Jackpot 29.png",
    // slots12_29:  "/src/sprites/Symbols/Jackpot/Jackpot 30.png",
    // slots12_30:  "/src/sprites/Symbols/Jackpot/Jackpot 31.png",
    // slots12_31:  "/src/sprites/Symbols/Jackpot/Jackpot 32.png",
    // slots12_32:  "/src/sprites/Symbols/Jackpot/Jackpot 33.png",
    // slots12_33:  "/src/sprites/Symbols/Jackpot/Jackpot 34.png",
    // slots12_34:  "/src/sprites/Symbols/Jackpot/Jackpot 35.png",
    // slots12_35:  "/src/sprites/Symbols/Jackpot/Jackpot 36.png",

    // slots13_0 :  "/src/sprites/Symbols/Bonus/Bonus 01.png",
    // slots13_1 :  "/src/sprites/Symbols/Bonus/Bonus 02.png",
    // slots13_2 :  "/src/sprites/Symbols/Bonus/Bonus 03.png",
    // slots13_3 :  "/src/sprites/Symbols/Bonus/Bonus 04.png",
    // slots13_4 :  "/src/sprites/Symbols/Bonus/Bonus 05.png",
    // slots13_5 :  "/src/sprites/Symbols/Bonus/Bonus 06.png",
    // slots13_6 :  "/src/sprites/Symbols/Bonus/Bonus 07.png",
    // slots13_7 :  "/src/sprites/Symbols/Bonus/Bonus 08.png",
    // slots13_8 :  "/src/sprites/Symbols/Bonus/Bonus 09.png",
    // slots13_9 :  "/src/sprites/Symbols/Bonus/Bonus 10.png",
    // slots13_10:  "/src/sprites/Symbols/Bonus/Bonus 11.png",
    // slots13_11:  "/src/sprites/Symbols/Bonus/Bonus 12.png",
    // slots13_12:  "/src/sprites/Symbols/Bonus/Bonus 13.png",
    // slots13_13:  "/src/sprites/Symbols/Bonus/Bonus 14.png",
    // slots13_14:  "/src/sprites/Symbols/Bonus/Bonus 15.png",
    // slots13_15:  "/src/sprites/Symbols/Bonus/Bonus 16.png",
    // slots13_16:  "/src/sprites/Symbols/Bonus/Bonus 17.png",
    // slots13_17:  "/src/sprites/Symbols/Bonus/Bonus 18.png",
    // slots13_18:  "/src/sprites/Symbols/Bonus/Bonus 19.png",
    // slots13_19:  "/src/sprites/Symbols/Bonus/Bonus 20.png",
    // slots13_20:  "/src/sprites/Symbols/Bonus/Bonus 21.png",
    // slots13_21:  "/src/sprites/Symbols/Bonus/Bonus 22.png",
    // slots13_22:  "/src/sprites/Symbols/Bonus/Bonus 23.png",
    // slots13_23:  "/src/sprites/Symbols/Bonus/Bonus 24.png",
    // slots13_24:  "/src/sprites/Symbols/Bonus/Bonus 25.png",
    // slots13_25:  "/src/sprites/Symbols/Bonus/Bonus 26.png",
    // slots13_26:  "/src/sprites/Symbols/Bonus/Bonus 27.png",
    // slots13_27:  "/src/sprites/Symbols/Bonus/Bonus 28.png",
    // slots13_28:  "/src/sprites/Symbols/Bonus/Bonus 29.png",
    // slots13_29:  "/src/sprites/Symbols/Bonus/Bonus 30.png",
    // slots13_30:  "/src/sprites/Symbols/Bonus/Bonus 31.png",
    // slots13_31:  "/src/sprites/Symbols/Bonus/Bonus 32.png",
    // slots13_32:  "/src/sprites/Symbols/Bonus/Bonus 33.png",
    // slots13_33:  "/src/sprites/Symbols/Bonus/Bonus 34.png",
    // slots13_34:  "/src/sprites/Symbols/Bonus/Bonus 35.png",
    // slots13_35:  "/src/sprites/Symbols/Bonus/Bonus 36.png",

    // firesheet: "src/sprites/FireSheet.png",
    // fire_1 :  "/src/sprites/Fire/Fire (1).png",
    // fire_2 :  "/src/sprites/Fire/Fire (2).png",
    // fire_3 :  "/src/sprites/Fire/Fire (3).png",
    // fire_4 :  "/src/sprites/Fire/Fire (4).png",
    // fire_5 :  "/src/sprites/Fire/Fire (5).png",
    // fire_6 :  "/src/sprites/Fire/Fire (6).png",
    // fire_7 :  "/src/sprites/Fire/Fire (7).png",
    // fire_8 :  "/src/sprites/Fire/Fire (8).png",
    // fire_9 :  "/src/sprites/Fire/Fire (9).png",
    // fire_10:  "/src/sprites/Fire/Fire (10).png",
    // fire_11:  "/src/sprites/Fire/Fire (11).png",
    // fire_12:  "/src/sprites/Fire/Fire (12).png",
    // fire_13:  "/src/sprites/Fire/Fire (13).png",
    // fire_14:  "/src/sprites/Fire/Fire (14).png",
    // fire_15:  "/src/sprites/Fire/Fire (15).png",
    // fire_16:  "/src/sprites/Fire/Fire (16).png",
    // fire_17:  "/src/sprites/Fire/Fire (17).png",
    // fire_18:  "/src/sprites/Fire/Fire (18).png",
    // fire_19:  "/src/sprites/Fire/Fire (19).png",
    // fire_20:  "/src/sprites/Fire/Fire (20).png",
    // fire_21:  "/src/sprites/Fire/Fire (21).png",
    // fire_22:  "/src/sprites/Fire/Fire (22).png",
    // fire_23:  "/src/sprites/Fire/Fire (23).png",
    
}



export const staticData = {
    Background:  "src/sprites/Background.jpg",
};

export const fontData = {
    crashLandingItalic : "src/fonts/CrashLandingBB.ttf"
}



export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/Teaser.mp3",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/spin.wav",
        winMusic: "src/sounds/JackpotWinner.mp3",
        buttonpressed: "src/sounds/Game-Button.mp3",
        spinWheelMusic: "src/sounds/spinWheel.mp3",
        bonusBg: "src/sounds/bonusbg.wav",
        bonuswin: "src/sounds/bonuswin.wav",
        cardMusic: "src/sounds/card.mp3",
        coconutFall: "src/sounds/coconutfall.wav"
 
};

export const preloaderConfig = {
    // startLogo:  "/src/sprites/Logo.png")
}